* adapt to new mulle-bashfunctions 1.3

diff --git a/mulle-bootstrap-to-sourcetree b/mulle-bootstrap-to-sourcetree
--- a/mulle-bootstrap-to-sourcetree
+++ b/mulle-bootstrap-to-sourcetree
@@ -78,83 +78,6 @@ EOF
 
 
 #
-# stolen from:
-# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
-# ----
-#
-_prepend_path_if_relative()
-{
-   case "$2" in
-      /*)
-         echo "$2"
-      ;;
-      *)
-         echo "$1/$2"
-      ;;
-   esac
-}
-
-
-resolve_symlinks()
-{
-   local dir_context
-   local linkpath
-
-   if linkpath="`readlink "$1"`"
-   then
-      dir_context=`dirname -- "$1"`
-      resolve_symlinks "`_prepend_path_if_relative "${dir_context}" "${linkpath}"`"
-   else
-      echo "$1"
-   fi
-}
-
-
-sourcetree_libexec_path()
-{
-   local executablepath="$1"
-
-   local exedir
-   local exedirpath
-   local prefix
-   local libexecpath
-
-   case "${executablepath}" in
-      \.*|/*|~*)
-      ;;
-
-      *)
-         executablepath="`command -v "${executablepath}"`"
-      ;;
-   esac
-
-   executablepath="`resolve_symlinks "${executablepath}"`"
-   exedirpath="`dirname "${executablepath}"`"
-   prefix="`dirname "${exedirpath}"`"
-   libexecpath="${prefix}/libexec/mulle-sourcetree"
-
-   if [ ! -x "${libexecpath}/mulle-sourcetree-config.sh" ]
-   then
-      libexecpath="${exedirpath}/src"
-   fi
-
-   case "$libexecpath" in
-      /*|~*)
-      ;;
-
-      *)
-         libexecpath="$PWD/$libexecpath"
-      ;;
-   esac
-
-   if [ -x "${libexecpath}/mulle-sourcetree-config.sh" ]
-   then
-      echo "${libexecpath}"
-   fi
-}
-
-
-#
 # Read the CVS from the .repositories file
 #
 # This function sets values of variables that should be declared
@@ -457,33 +380,31 @@ _init()
       exit 0
    fi
 
-   MULLE_SOURCETREE_LIBEXEC_DIR="`sourcetree_libexec_path "$0"`"
-   if [ -z "${MULLE_SOURCETREE_LIBEXEC_DIR}" ]
-   then
-      echo "Fatal Error: Could not find libexec for ${MULLE_EXECUTABLE} ($PWD)" >&2
-      exit 1
-   fi
-
-   #
-   # minimal setup exit
-   #
-   if [ "$1" = "library-path" ]
-   then
-      echo "${MULLE_SOURCETREE_LIBEXEC_DIR}"
-      exit 0
-   fi
-
-   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env library-path 2> /dev/null`"
    if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
    then
-      if [ -z "`command -v "${executablepath}"`" ]
+      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
+      if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
       then
-          echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
-      else
-         echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+         if [ -z "`command -v "${executablepath}"`" ]
+         then
+             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
+         else
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+         fi
+         exit 1
       fi
-      exit 1
    fi
+
+      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || \
+      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
+
+   local _libexec_dir
+
+   _get_libexec_dir "$0" "mulle-sourcetree" "mulle-sourcetree-config.sh"
+
+   MULLE_SOURCETREE_LIBEXEC_DIR="${_libexec_dir}"
+
 
    #
    # to make these includes faster don't search via PATH
@@ -493,18 +414,20 @@ _init()
 
    failmsg="failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
 
-      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh"   || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-logging.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh"  || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-exekutor.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-exekutor.sh" || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-options.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-options.sh"  || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-path.sh
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-path.sh"     || fail "${failmsg}"
       # shellcheck source=../mulle-bashfunctions/src/mulle-file.sh
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-file.sh"     || fail "${failmsg}"
+
+
+   #
+   # minimal setup exit
+   #
+   case "$1" in
+      "libexec-dir"|"library-path")
+         echo "${MULLE_SOURCETREE_LIBEXEC_DIR}"
+         exit 0
+      ;;
+   esac
 
 
    #  set -e # more pain then gain in the end
@@ -515,6 +438,7 @@ _init()
 
    MULLE_ARGUMENTS="$*"
 }
+
 
 _init "$@" # needs params
 main "$@"
diff --git a/mulle-sourcetree b/mulle-sourcetree
--- a/mulle-sourcetree
+++ b/mulle-sourcetree
@@ -32,7 +32,7 @@
 [ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"
 
 
-MULLE_EXECUTABLE_VERSION="0.3.3"
+MULLE_EXECUTABLE_VERSION="0.4.0"
 
 #
 # This is the main user interface to mulle-sourcetree
@@ -373,7 +373,6 @@ main()
             MULLE_SOURCETREE_SHARE_DIR="$1"
          ;;
 
-
          --version)
             echo "${MULLE_EXECUTABLE_VERSION}"
             exit 0
@@ -638,88 +637,11 @@ main()
    esac
 }
 
+
 ########
 ###
 ### INIT
 ###
-
-#
-# stolen from:
-# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
-# ----
-#
-_prepend_path_if_relative()
-{
-   case "$2" in
-      /*)
-         echo "$2"
-      ;;
-      *)
-         echo "$1/$2"
-      ;;
-   esac
-}
-
-
-resolve_symlinks()
-{
-   local dir_context
-   local linkpath
-
-   if linkpath="`readlink "$1"`"
-   then
-      dir_context=`dirname -- "$1"`
-      resolve_symlinks "`_prepend_path_if_relative "${dir_context}" "${linkpath}"`"
-   else
-      echo "$1"
-   fi
-}
-
-
-sourcetree_libexec_path()
-{
-   local executablepath="$1"
-
-   local exedir
-   local exedirpath
-   local prefix
-   local libexecpath
-
-   case "${executablepath}" in
-      \.*|/*|~*)
-      ;;
-
-      *)
-         executablepath="`command -v "${executablepath}"`"
-      ;;
-   esac
-
-   executablepath="`resolve_symlinks "${executablepath}"`"
-   exedirpath="`dirname "${executablepath}"`"
-   prefix="`dirname "${exedirpath}"`"
-   libexecpath="${prefix}/libexec/mulle-sourcetree"
-
-   if [ ! -x "${libexecpath}/mulle-sourcetree-config.sh" ]
-   then
-      libexecpath="${exedirpath}/src"
-   fi
-
-   case "$libexecpath" in
-      /*|~*)
-      ;;
-
-      *)
-         libexecpath="$PWD/$libexecpath"
-      ;;
-   esac
-
-   if [ -x "${libexecpath}/mulle-sourcetree-config.sh" ]
-   then
-      echo "${libexecpath}"
-   fi
-}
-
-
 _init()
 {
    #
@@ -731,16 +653,31 @@ _init()
       exit 0
    fi
 
-   MULLE_SOURCETREE_LIBEXEC_DIR="`sourcetree_libexec_path "$0"`"
-   if [ -z "${MULLE_SOURCETREE_LIBEXEC_DIR}" ]
+   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
    then
-      echo "$0 fatal error: Could not find libexec ($PWD)" >&2
-      exit 1
+      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
+      if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+      then
+         if [ -z "`command -v "${executablepath}"`" ]
+         then
+             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
+         else
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+         fi
+         exit 1
+      fi
    fi
 
-   #
-   # minimal setup exit
-   #
+      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || \
+      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
+
+   local _libexec_dir
+
+   _get_libexec_dir "$0" "mulle-sourcetree" "mulle-sourcetree-config.sh"
+
+   MULLE_SOURCETREE_LIBEXEC_DIR="${_libexec_dir}"
+
    #
    # minimal setup exit
    #
@@ -751,31 +688,6 @@ _init()
       ;;
    esac
 
-   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
-   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
-   then
-      if [ -z "`command -v "${executablepath}"`" ]
-      then
-          echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
-      else
-         echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
-      fi
-      exit 1
-   fi
-   local failmsg
-
-   failmsg="failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
-
-      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh"   || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-logging.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh"  || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-exekutor.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-exekutor.sh" || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-options.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-options.sh"  || fail "${failmsg}"
-
-
    #  set -e # more pain then gain in the end
    #  set -u # doesn't work with my style
 
@@ -784,7 +696,6 @@ _init()
 
    MULLE_ARGUMENTS="$*"
 }
-
 ###
 ### INIT
 ###
