* new --eval-node option for **walk** command * mulle-sourcetree-graph now emits hyperlinks

diff --git a/mulle-sourcetree-graph b/mulle-sourcetree-graph
--- a/mulle-sourcetree-graph
+++ b/mulle-sourcetree-graph
@@ -1,4 +1,4 @@
-#! /bin/sh 
+#! /usr/bin/env mulle-bash
 #
 #   Copyright (c) 2021-2022 Nat! - Mulle kybernetiK
 #   All rights reserved.
@@ -32,22 +32,11 @@
 [ "${TRACE:-}" = 'YES' -o "${MULLE_SOURCETREE_GRAPH_TRACE:-}" = 'YES' ] && set -x && : "$0" "$@"
 
 
+MULLE_EXECUTABLE_VERSION=1.0.0
 
-# per project settings, if available
-if [ -f .mulle/etc/sourcetree/graph/environment ]
-then
-   . .mulle/etc/sourcetree/graph/environment
-fi
-
-GRAPH_LIBRARIES="${GRAPH_LIBRARIES:-NO}"
-GRAPH_DEDUPE="${GRAPH_DEDUPE:-YES}"
-GRAPH_MAX_LEVEL="${GRAPH_MAX_LEVEL:-3}"
-GRAPH_DIRECTION="${GRAPH_DIRECTION:-TD}"
-GRAPH_OPTIONS="${GRAPH_OPTIONS:---ignore mulle-objc-list}"
-
-case "$1" in
-   -h|--help|help)
-      cat <<EOF >&2
+usage()
+{
+   cat <<EOF >&2
 Usage:
    mulle-sourcetree-graph [direction [level [dedupe]]]
 
@@ -59,55 +48,53 @@ Usage:
    Needs the "dot" command (graphviz) to be installed.
 
    You can have permanent per-project settings for GRAPH_LIBRARIES,
-   GRAPH_DEDUPE, GRAPH_MAX_LEVEL, GRAPH_DIRECTION, GRAPH_OPTIONS
+   GRAPH_DEDUPE, GRAPH_MAX_LEVEL, GRAPH_DIRECTION, GRAPH_OPTIONS by storing
+   them in ".mulle/etc/sourcetree/graph/environment". These values will
+   override any environment variables.
 
    Example:
       mkdir -p .mulle/etc/sourcetree/graph
       echo "GRAPH_MAX_LEVEL=5" >> .mulle/etc/sourcetree/graph/environment
 
    You can override GRAPH_DIRECTION, GRAPH_MAX_LEVEL, GRAPH_DEDUPE with
-   arguments on the commandline.
+   arguments on the commandline, which will override any environment and
+   per-project settings.
 
 Environment:
-   GRAPH_DIRECTION : set graph direction to TD or LR ($GRAPH_DIRECTION)
-   GRAPH_MAX_LEVEL : set maximum recursion depth (${GRAPH_MAX_LEVEL})
    GRAPH_DEDUPE    : set to NO to show all edges. (${GRAPH_DEDUPE})
+   GRAPH_DIRECTION : set graph direction to TD or LR ($GRAPH_DIRECTION)
    GRAPH_LIBRARIES : set to YES to also dump libraries. (${GRAPH_LIBRARIES})
+   GRAPH_MAX_LEVEL : set maximum recursion depth (${GRAPH_MAX_LEVEL})
    GRAPH_OPTIONS   : options for mulle-sourcetree walk (${GRAPH_OPTIONS})
 
 EOF
    exit 1
-esac
+}
 
 
-direction="${1:-${GRAPH_DIRECTION}}"
-[ $# -ne 0 ] && shift
+dot_dump()
+(
+   log_entry dot_dump "$@"
 
-level="${1:-${GRAPH_MAX_LEVEL}}"
-[ $# -ne 0 ] && shift
+   local direction="$1"
+   local level="$2"
+   local dedupe="$3"
+   local libraries="$4"
+   local options="$5"
 
-dedupe="${1:-${GRAPH_DEDUPE}}"
-[ $# -ne 0 ] && shift
+   shift 5
 
-libraries="${GRAPH_LIBRARIES}"
-options="${GRAPH_OPTIONS}"
+   cat <<EOF
+digraph sourcetree
+{
+   rankdir = ${direction};
+   node [ shape="box"; style="filled" ]
+EOF
 
-if [ "${options}" = "NONE" ]
-then
-   options=""
-fi
+   r_basename "${PWD}"
+   WALK_PARENT="${RVAL}"
 
-
-
-( 
-   echo "digraph sourcetree"
-   echo "{"
-   echo "   rankdir = ${direction};"
-   echo "   node [ shape=\"box\"; style=\"filled\" ]"
-
-   WALK_PARENT="`basename "$PWD" `"
-
-   echo "\"${WALK_PARENT}\"  [ fillcolor=\"yellow\"]"
+   echo "   \"${WALK_PARENT}\"  [ fillcolor=\"yellow\"]"
 
    if [ ! -z "${GRAPH_HEADER}" ]
    then
@@ -126,19 +113,27 @@ fi
       if [ "${libraries}" = 'YES' ]
       then
          WALK_PARENT="${WALK_PARENT}" \
-            mulle-sourcetree walk ${dedupe} \
+            rexekutor mulle-sourcetree \
+                                  walk \
+                                  ${dedupe} \
+                                  --eval-node \
                                   --max-walk-level ${level} \
                                   ${options} \
                                   "$@" \
-                                  'echo "\"${WALK_PARENT}\" -> \"${NODE_ADDRESS}\""'
+                                  'echo "\"${WALK_PARENT}\" -> \"${NODE_ADDRESS}\"
+\"${NODE_ADDRESS}\" [ href=\"`mulle-domain homepage-url \"${NODE_EVALED_URL}\"`\" ]"'
       else
          WALK_PARENT="${WALK_PARENT}" \
-            mulle-sourcetree walk --qualifier 'MATCHES fs' \
+            rexekutor mulle-sourcetree \
+                                  walk \
+                                  --qualifier 'MATCHES fs' \
                                   ${dedupe} \
                                   ${options} \
-                                   --max-walk-level ${level} \
+                                  --eval-node \
+                                  --max-walk-level ${level} \
                                   "$@" \
-                                  'echo "\"${WALK_PARENT}\" -> \"${NODE_ADDRESS}\""'
+                                  'eval  ; echo "\"${WALK_PARENT}\" -> \"${NODE_ADDRESS}\"
+\"${NODE_ADDRESS}\" [ href=\"`mulle-domain homepage-url \"${NODE_EVALED_URL}\"`\" ]"'
       fi
 
    ) \
@@ -152,5 +147,113 @@ fi
    fi
 
    echo "}"
-) \
-| dot -Tsvg
+)
+
+
+
+cat_output()
+{
+   log_entry cat_output "$@"
+
+   local format="${1:-svg}"
+
+   case "${format}" in
+      dot)
+         cat
+      ;;
+
+      *)
+         dot -T${format}
+      ;;
+   esac
+}
+
+
+main()
+{
+   local OPTION_FORMAT
+
+   while [ $# -ne 0 ]
+   do
+      if options_technical_flags "$1"
+      then
+         shift
+         continue
+      fi
+
+      case "$1" in
+         -h|--help|help)
+            usage
+         ;;
+
+         --version)
+            printf "%s\n" "${MULLE_BASHFUNCTIONS_VERSION}"
+            exit 0
+         ;;
+
+         --png|--svg|--dot)
+            OPTION_FORMAT="${1:2}"
+         ;;
+
+         -*)
+            log_error "${MULLE_EXECUTABLE_FAIL_PREFIX}: Unknown option \"$1\""
+            usage
+         ;;
+
+         *)
+            break
+         ;;
+      esac
+
+      shift
+   done
+
+   options_setup_trace "${MULLE_TRACE}" && set -x
+
+   # per project settings, if available
+   if [ -f .mulle/etc/sourcetree/graph/environment ]
+   then
+      . .mulle/etc/sourcetree/graph/environment
+   fi
+
+   GRAPH_DEDUPE="${GRAPH_DEDUPE:-YES}"
+   GRAPH_DIRECTION="${GRAPH_DIRECTION:-TD}"
+   GRAPH_LIBRARIES="${GRAPH_LIBRARIES:-NO}"
+   GRAPH_MAX_LEVEL="${GRAPH_MAX_LEVEL:-3}"
+   GRAPH_OPTIONS="${GRAPH_OPTIONS:---ignore mulle-objc-list}"
+
+   log_setting "GRAPH_DEDUPE    : ${GRAPH_DEDUPE}"
+   log_setting "GRAPH_DIRECTION : ${GRAPH_DIRECTION}"
+   log_setting "GRAPH_LIBRARIES : ${GRAPH_LIBRARIES}"
+   log_setting "GRAPH_MAX_LEVEL : ${GRAPH_MAX_LEVEL}"
+   log_setting "GRAPH_OPTIONS   : ${GRAPH_OPTIONS}"
+
+   local direction
+   local level
+   local dedupe
+   local libraries
+   local options
+
+   direction="${1:-${GRAPH_DIRECTION}}"
+   [ $# -ne 0 ] && shift
+
+   level="${1:-${GRAPH_MAX_LEVEL}}"
+   [ $# -ne 0 ] && shift
+
+   dedupe="${1:-${GRAPH_DEDUPE}}"
+   [ $# -ne 0 ] && shift
+
+   libraries="${GRAPH_LIBRARIES}"
+   options="${GRAPH_OPTIONS}"
+
+   if [ "${options}" = "NONE" ]
+   then
+      options=""
+   fi
+
+   dot_dump "${direction}" "${level}" "${dedupe}" "${libraries}" "${options}" \
+   | cat_output "${OPTION_FORMAT}"
+}
+
+
+main "$@"
