* there is now a rename command * more options for listing * branch and tag are now evaled * branch and tag are available for expansion in url as MULLE_BRANCH and MULLE_TAG * similiarly fetchoption can be expanded with both and additionally MULLE_URL * major performance improvement in the sourcetree buildorder generator

diff --git a/mulle-sourcetree b/mulle-sourcetree
--- a/mulle-sourcetree
+++ b/mulle-sourcetree
@@ -75,6 +75,7 @@ print_commands()
    mark           : add or remove a mark from a node in the sourcetree
    move           : move a node within the sourcetree
    sourcetree-dir : print path to project (if a sourcetree exists)
+   rename         : rename a node in the sourcetree
    remove         : remove a node from the sourcetree
    reset          : clear the database, to force a sync
    touch          : mark sourcetree as dirty
@@ -431,7 +432,7 @@ main()
    fi
 
    case "${cmd}" in
-      add|get|duplicate|info|knownmarks|mark|move|nameguess|remove|set|typeguess|unmark)
+      add|get|duplicate|info|knownmarks|mark|move|nameguess|rename|remove|set|typeguess|unmark)
          # shellcheck source=src/mulle-sourcetree-config.sh
          . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
 
@@ -547,7 +548,7 @@ _init()
       then
          if [ -z "`command -v "${executablepath}"`" ]
          then
-             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
+            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
          else
             echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
          fi
