improved the walk code, to be able to predict share config

diff --git a/mulle-bootstrap-to-sourcetree b/mulle-bootstrap-to-sourcetree
--- a/mulle-bootstrap-to-sourcetree
+++ b/mulle-bootstrap-to-sourcetree
@@ -154,82 +154,6 @@ sourcetree_libexec_path()
 }
 
 
-_init()
-{
-   #
-   # minimal setup exit
-   #
-   if [ "$1" = "version" ]
-   then
-      echo "${MULLE_EXECUTABLE_VERSION}"
-      exit 0
-   fi
-
-   MULLE_SOURCETREE_LIBEXEC_DIR="`sourcetree_libexec_path "$0"`"
-   if [ -z "${MULLE_SOURCETREE_LIBEXEC_DIR}" ]
-   then
-      echo "Fatal Error: Could not find libexec for ${MULLE_EXECUTABLE} ($PWD)" >&2
-      exit 1
-   fi
-
-   #
-   # minimal setup exit
-   #
-   if [ "$1" = "library-path" ]
-   then
-      echo "${MULLE_SOURCETREE_LIBEXEC_DIR}"
-      exit 0
-   fi
-
-   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env library-path 2> /dev/null`"
-   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
-   then
-      if [ -z "`command -v "${executablepath}"`" ]
-      then
-          echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
-      else
-         echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
-      fi
-      exit 1
-   fi
-
-   PATH="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}:$PATH"
-   PATH="${MULLE_SOURCETREE_LIBEXEC_DIR}:$PATH"
-   export PATH
-
-   if [ ! -z "${MULLE_SOURCETREE_LIBEXEC_TRACE}" ]
-   then
-      echo "PATH=$PATH" >&2
-   fi
-
-   #
-   # to make these includes faster don't search via PATH
-   # but have PATH as fallback
-   #
-   local failmsg
-
-   failmsg="failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
-
-      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh"   || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-logging.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh"  || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-exekutor.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-exekutor.sh" || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-options.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-options.sh"  || fail "${failmsg}"
-
-
-   #  set -e # more pain then gain in the end
-   #  set -u # doesn't work with my style
-
-   trap trap_fail INT
-   set -o pipefail
-
-   MULLE_ARGUMENTS="$*"
-}
-
-
 #
 # Read the CVS from the .repositories file
 #
@@ -289,11 +213,10 @@ parse_clone()
 }
 
 
-
 copy_repositories()
 {
    local filename="$1"
-   local mark="$2"
+   local marks="$2"
 
    local url
    local branch
@@ -303,7 +226,7 @@ copy_repositories()
 
    ROOT_DIR="${PWD}"
 
-   log_verbose "Copy ${C_RESET_BOLD}${filename}"
+   log_info "Copy ${C_RESET_BOLD}${filename}${C_INFO} contents"
 
    local clone
 
@@ -319,30 +242,41 @@ copy_repositories()
 
       parse_clone "${clone}"
 
+      local evaledurl
+
+      evaledurl="`eval echo "$url"`"
+      [ -z "${evaledurl}" ] && fail "URL \"${url}\" evaluates to empty"
+
+      if [ -z "${scm}" ]
+      then
+         scm="`exekutor ${MULLE_FETCH:-mulle-fetch} typeguess "${evaledurl}"`"
+      fi
+      scm="${scm:-git}"
+
+      # mark empty = normal
       if [ -z "${dstdir}" ]
       then
-         local evaledurl
-
-         evaledurl="`eval echo "$url"`"
-         [ -z "${evaledurl}" ] && fail "URL \"${url}\" evaluates to empty"
-
-         dstdir="`${MULLE_FETCH:-mulle-fetch} guess "${evaledurl}"`"
-         dstdir="stashes/${dstdir}"
+         dstdir="`exekutor ${MULLE_FETCH:-mulle-fetch} guess -s "${scm}" "${evaledurl}"`"
+         if [ -z "${marks}" ]
+         then
+            dstdir="subproject/${dstdir}"
+         fi
       fi
+
+
+      log_fluff "Adding ${scm} ${C_MAGENTA}${C_BOLD}${dstdir}${C_VERBOSE} ..."
 
       if ! exekutor mulle-sourcetree add -s "${scm}" \
                                          -b "${branch}" \
                                          -t "${tag}" \
-                                         "${url}" "${dstdir}"
+                                         -m "${marks}" \
+                                         -u "${url}" "${dstdir}"
       then
          exit 1
       fi
-      if ! [ -z "${mark}" ]
+
+      if ! [ -z "${marks}" ]
       then
-         if ! exekutor mulle-sourcetree mark "${url}" "${mark}"
-         then
-            exit 1
-         fi
          log_info "Added embedded ${C_MAGENTA}${C_BOLD}${url}${C_INFO} for \
 ${C_RESET_BOLD}${dstdir}${C_INFO}"
       else
@@ -353,17 +287,11 @@ ${C_RESET_BOLD}${dstdir}${C_INFO}"
 }
 
 
-
 convert_bootstrap()
 {
    local directory="$1"
 
-   if [ -f "${SOURCETREE_CONFIG_FILE}" ]
-   then
-      fail "There is already a ${SOURCETREE_CONFIG_FILE} here ($PWD)"
-   fi
-
-   if [ ! -d .bootstrap -a  ! -d .bootstrap.local ]
+   if [ ! -d .bootstrap -a ! -d .bootstrap.local ]
    then
       log_warning "No .bootstrap folders found ($PWD)"
       exit 0
@@ -376,6 +304,15 @@ The master can not be converted. Convert the minions! ($PWD)"
       exit 0
    fi
 
+   if [ -f "${SOURCETREE_CONFIG_FILE}" ]
+   then
+      if [ "${MULLE_FLAG_MAGNUM_FORCE}" = "NONE" ]
+      then
+         fail "There is already a ${SOURCETREE_CONFIG_FILE} here ($PWD)"
+      fi
+      remove_file_if_present "${SOURCETREE_CONFIG_FILE}"
+   fi
+
    local found
 
    found="NO"
@@ -384,12 +321,12 @@ The master can not be converted. Convert the minions! ($PWD)"
    #
    if [ -f ".bootstrap.local/embedded_repositories" ]
    then
-      copy_repositories ".bootstrap.local/embedded_repositories" "nobuild"
+      copy_repositories ".bootstrap.local/embedded_repositories" "nobuild,noshare"
       found="YES"
    else
       if [ -f ".bootstrap/embedded_repositories" ]
       then
-         copy_repositories ".bootstrap/embedded_repositories" "nobuild"
+         copy_repositories ".bootstrap/embedded_repositories" "nobuild,noshare"
          found="YES"
       fi
    fi
@@ -435,7 +372,7 @@ main()
 
    local SOURCETREE_CONFIG_FILE=".mulle-sourcetree"
    local SOURCETREE_DB_DIR=".mulle-sourcetree.db"
-   local SOURCETREE_SHARED_DIR="stashes"
+   local MULLE_SOURCETREE_SHARED_DIR="stashes"
 
    #
    # simple option handling
@@ -506,6 +443,86 @@ main()
    ( cd "${directory}" &&  convert_bootstrap )
 }
 
+
+
+_init()
+{
+   #
+   # minimal setup exit
+   #
+   if [ "$1" = "version" ]
+   then
+      echo "${MULLE_EXECUTABLE_VERSION}"
+      exit 0
+   fi
+
+   MULLE_SOURCETREE_LIBEXEC_DIR="`sourcetree_libexec_path "$0"`"
+   if [ -z "${MULLE_SOURCETREE_LIBEXEC_DIR}" ]
+   then
+      echo "Fatal Error: Could not find libexec for ${MULLE_EXECUTABLE} ($PWD)" >&2
+      exit 1
+   fi
+
+   #
+   # minimal setup exit
+   #
+   if [ "$1" = "library-path" ]
+   then
+      echo "${MULLE_SOURCETREE_LIBEXEC_DIR}"
+      exit 0
+   fi
+
+   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env library-path 2> /dev/null`"
+   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+   then
+      if [ -z "`command -v "${executablepath}"`" ]
+      then
+          echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
+      else
+         echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+      fi
+      exit 1
+   fi
+
+   PATH="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}:$PATH"
+   PATH="${MULLE_SOURCETREE_LIBEXEC_DIR}:$PATH"
+   export PATH
+
+   if [ ! -z "${MULLE_SOURCETREE_LIBEXEC_TRACE}" ]
+   then
+      echo "PATH=$PATH" >&2
+   fi
+
+   #
+   # to make these includes faster don't search via PATH
+   # but have PATH as fallback
+   #
+   local failmsg
+
+   failmsg="failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
+
+      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh"   || fail "${failmsg}"
+      # shellcheck source=../mulle-bashfunctions/src/mulle-logging.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh"  || fail "${failmsg}"
+      # shellcheck source=../mulle-bashfunctions/src/mulle-exekutor.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-exekutor.sh" || fail "${failmsg}"
+      # shellcheck source=../mulle-bashfunctions/src/mulle-options.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-options.sh"  || fail "${failmsg}"
+      # shellcheck source=../mulle-bashfunctions/src/mulle-path.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-path.sh"     || fail "${failmsg}"
+      # shellcheck source=../mulle-bashfunctions/src/mulle-file.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-file.sh"     || fail "${failmsg}"
+
+
+   #  set -e # more pain then gain in the end
+   #  set -u # doesn't work with my style
+
+   trap trap_fail INT
+   set -o pipefail
+
+   MULLE_ARGUMENTS="$*"
+}
 
 _init "$@" # needs params
 main "$@"
diff --git a/mulle-sourcetree b/mulle-sourcetree
--- a/mulle-sourcetree
+++ b/mulle-sourcetree
@@ -57,8 +57,8 @@ SHOWN_COMMANDS="\
    add           : add a node to the configuration
    buildorder    : emit nodes that are buildable in proper dependency order
    clean         : remove files added by an update
-   list          : list nodes in the configuration
-   remove        : remove a node from the configuration
+   info          : print current sourcetree information
+   print         : list nodes recursively in the configuration
    set           : set a node's properties in the configuration
    status        : query state of the tree
    update        : update the project tree [default]"
@@ -68,8 +68,10 @@ HIDDEN_COMMANDS="\
    fix           : support to track user modifications in the filesystem
    get           : get a node's properties from the configuration
    library-path  : print path to ${MULLE_EXECUTABLE_NAME} libexec
+   list          : list nodes in the current configuration
    mark          : add or remove a mark from a node in the configuration
    walk          : visit all the tree nodes with a callback
+   remove        : remove a node from the configuration
    reset         : clear the database, to force an update
    uname         : ${MULLE_EXECUTABLE_NAME}'s simplified uname(1)
    version       : print ${MULLE_EXECUTABLE_NAME} version"
@@ -130,6 +132,289 @@ EOF
    exit 1
 }
 
+
+main()
+{
+   local MULLE_FLAG_MAGNUM_FORCE="NONE"
+   local MULLE_FLAG_IGNORE_GRAVEYARD="NO"
+
+   # technical flags
+   local MULLE_FLAG_EXEKUTOR_DRY_RUN="NO"
+   local MULLE_FLAG_LOG_LOCAL="NO"
+   local MULLE_FLAG_LOG_DEBUG="NO"
+   local MULLE_FLAG_LOG_EXEKUTOR="NO"
+   local MULLE_FLAG_LOG_FLUFF="NO"
+   local MULLE_FLAG_LOG_SCRIPTS="NO"
+   local MULLE_FLAG_LOG_SETTINGS="NO"
+   local MULLE_FLAG_LOG_VERBOSE="NO"
+   local MULLE_FLAG_LOG_MERGE="NO"
+   local MULLE_TRACE_POSTPONE="NO"
+   local MULLE_FLAG_DEFER="ROOT"
+
+   local FLAG_SOURCETREE_MODE=
+
+   local SOURCETREE_CONFIG_FILE=".mulle-sourcetree"
+   local SOURCETREE_DEFAULT_FILE=".mulle-sourcetree.default"
+   local SOURCETREE_DB_DIR=".mulle-sourcetree.db"
+   local SOURCETREE_FIX_FILE=".mulle-sourcetree.fix"
+
+
+   #
+   # simple option handling
+   #
+   while [ $# -ne 0 ]
+   do
+      if options_technical_flags "$1"
+      then
+         shift
+         continue
+      fi
+
+      case "$1" in
+         -f|--force)
+            MULLE_FLAG_MAGNUM_FORCE="BOTH"
+         ;;
+
+         -h|--help)
+            usage "${MULLE_TRACE}"
+         ;;
+
+         --git-terminal-prompt)
+            [ $# -eq 1 ] && fail "missing argument to \"$1\""
+            shift
+
+            GIT_TERMINAL_PROMPT="$1"
+            export GIT_TERMINAL_PROMPT
+         ;;
+
+         --database-dir)
+            [ $# -eq 1 ] && fail "missing argument to \"$1\""
+            shift
+
+            SOURCETREE_DB_DIR="$1"
+         ;;
+
+         --config|--config-file)
+            [ $# -eq 1 ] && fail "missing argument to \"$1\""
+            shift
+
+            SOURCETREE_CONFIG_FILE="$1"
+         ;;
+
+         -D|--defer|--defer-root)
+            MULLE_FLAG_DEFER="ROOT";
+         ;;
+
+         -r|--recurse|--recursive)
+            FLAG_SOURCETREE_MODE="recurse"
+         ;;
+
+         --flat)
+            FLAG_SOURCETREE_MODE="flat"
+         ;;
+
+         --share)
+            FLAG_SOURCETREE_MODE="share"
+         ;;
+
+         --defer-parent)
+            MULLE_FLAG_DEFER="PARENT";
+         ;;
+
+         -N|--no-defer)
+            MULLE_FLAG_DEFER="NONE";
+         ;;
+
+         --version)
+            echo "${MULLE_EXECUTABLE_VERSION}"
+            exit 0
+         ;;
+
+         -*)
+            log_error "${MULLE_EXECUTABLE_FAIL_PREFIX}: Unknown flag \"$1\""
+            usage "${MULLE_TRACE}"
+         ;;
+
+         *)
+            break
+         ;;
+      esac
+
+      shift
+   done
+
+   options_setup_trace "${MULLE_TRACE}"
+
+   local cmd
+
+   cmd="${1:-update}"
+
+   MULLE_EXECUTABLE_FAIL_PREFIX="${MULLE_EXECUTABLE_NAME} ${cmd}"
+   [ $# -eq 0 ] || shift
+
+   if [ -z "${MULLE_FETCH}" ]
+   then
+      MULLE_FETCH="mulle-fetch"
+   fi
+
+   # shellcheck source=mulle-sourcetree-db.sh
+   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh" || exit 1
+   # shellcheck source=mulle-sourcetree-node.sh
+   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh" || exit 1
+   # shellcheck source=mulle-sourcetree-nodeline.sh
+   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
+
+   nodeline_defer_if_needed "ROOT"
+
+   local SOURCETREE_MODE
+
+   _db_set_default_mode "${FLAG_SOURCETREE_MODE}"
+
+   #
+   #
+   #
+   case "${cmd}" in
+      add)
+         # shellcheck source=src/mulle-sourcetree-config.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
+
+         sourcetree_add_main "$@"
+      ;;
+
+      buildorder)
+         # shellcheck source=src/mulle-sourcetree-walk.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-walk.sh"
+
+          "$@"
+      ;;
+
+      clean)
+         # shellcheck source=src/mulle-sourcetree-db.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-zombie.sh"
+
+         zombie_clean_main "$@"
+      ;;
+
+      dotdump)
+         # shellcheck source=src/mulle-sourcetree-dotdump.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-dotdump.sh"
+
+         sourcetree_dotdump_main "$@"
+      ;;
+
+      fix)
+         # shellcheck source=src/mulle-sourcetree-fix.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-fix.sh"
+
+         sourcetree_fix_main "$@"
+      ;;
+
+      get)
+         # shellcheck source=src/mulle-sourcetree-config.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
+
+         sourcetree_get_main "$@"
+      ;;
+
+      help)
+         usage "${MULLE_TRACE}"
+      ;;
+
+      info)
+         # shellcheck source=src/mulle-sourcetree-config.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
+
+         sourcetree_info_main "$@"
+      ;;
+
+      library-path)
+         echo "${MULLE_SOURCETREE_LIBEXEC_DIR}"
+      ;;
+
+      list)
+         # shellcheck source=src/mulle-sourcetree-config.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
+
+         sourcetree_list_main "$@"
+      ;;
+
+      mark)
+         # shellcheck source=src/mulle-sourcetree-config.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
+
+         sourcetree_mark_main "$@"
+      ;;
+
+      print)
+         # shellcheck source=src/mulle-sourcetree-walk.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-walk.sh"
+
+         sourcetree_walk_main --no-depth-first --callback-root --cd \
+               "${MULLE_EXECUTABLE}" --flat -N list --output-eval
+      ;;
+
+      remove)
+         # shellcheck source=src/mulle-sourcetree-config.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
+
+         sourcetree_remove_main "$@"
+      ;;
+
+      reset)
+         # shellcheck source=src/mulle-sourcetree-reset.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-reset.sh"
+
+         sourcetree_reset_main "$@"
+      ;;
+
+      set)
+         # shellcheck source=src/mulle-sourcetree-config.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
+
+         sourcetree_set_main "$@"
+      ;;
+
+      status)
+         # shellcheck source=src/mulle-sourcetree-status.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-status.sh"
+
+         sourcetree_status_main "$@"
+      ;;
+
+      uname)
+         echo "${UNAME}"
+      ;;
+
+      update)
+         # shellcheck source=src/mulle-sourcetree-update.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-update.sh"
+
+         sourcetree_update_main "$@"
+      ;;
+
+      walk)
+         # shellcheck source=src/mulle-sourcetree-walk.sh
+         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-walk.sh"
+
+         sourcetree_walk_main "$@"
+      ;;
+
+      version)
+         echo "${MULLE_EXECUTABLE_VERSION}"
+         return 0
+      ;;
+
+      *)
+         log_error "${MULLE_EXECUTABLE_FAIL_PREFIX}: Unknown command \"${cmd}\""
+         usage "${MULLE_TRACE}"
+      ;;
+   esac
+}
+
+########
+###
+### INIT
+###
 
 #
 # stolen from:
@@ -283,227 +568,10 @@ _init()
    MULLE_ARGUMENTS="$*"
 }
 
-
-main()
-{
-   local MULLE_FLAG_MAGNUM_FORCE="NONE"
-   local MULLE_FLAG_IGNORE_GRAVEYARD="NO"
-
-   # technical flags
-   local MULLE_FLAG_EXEKUTOR_DRY_RUN="NO"
-   local MULLE_FLAG_LOG_LOCAL="NO"
-   local MULLE_FLAG_LOG_DEBUG="NO"
-   local MULLE_FLAG_LOG_EXEKUTOR="NO"
-   local MULLE_FLAG_LOG_FLUFF="NO"
-   local MULLE_FLAG_LOG_SCRIPTS="NO"
-   local MULLE_FLAG_LOG_SETTINGS="NO"
-   local MULLE_FLAG_LOG_VERBOSE="NO"
-   local MULLE_FLAG_LOG_MERGE="NO"
-   local MULLE_TRACE_POSTPONE="NO"
-
-   local SOURCETREE_CONFIG_FILE=".mulle-sourcetree"
-   local SOURCETREE_DB_DIR=".mulle-sourcetree.db"
-   local SOURCETREE_SHARED_DIR="stashes"
-   local SOURCETREE_FIX_FILE=".mulle-sourcetree.fix"
-   #
-   # simple option handling
-   #
-   while [ $# -ne 0 ]
-   do
-      if options_technical_flags "$1"
-      then
-         shift
-         continue
-      fi
-
-      case "$1" in
-         -f|--force)
-            MULLE_FLAG_MAGNUM_FORCE="BOTH"
-         ;;
-
-         -h|--help)
-            usage "${MULLE_TRACE}"
-         ;;
-
-         --git-terminal-prompt)
-            [ $# -eq 1 ] && fail "missing argument to \"$1\""
-            shift
-
-            GIT_TERMINAL_PROMPT="$1"
-            export GIT_TERMINAL_PROMPT
-         ;;
-
-         --database-dir)
-            [ $# -eq 1 ] && fail "missing argument to \"$1\""
-            shift
-
-            SOURCETREE_DB_DIR="$1"
-         ;;
-
-         --config|--config-file)
-            [ $# -eq 1 ] && fail "missing argument to \"$1\""
-            shift
-
-            SOURCETREE_CONFIG_FILE="$1"
-         ;;
-
-         --version)
-            echo "${MULLE_EXECUTABLE_VERSION}"
-            exit 0
-         ;;
-
-         -*)
-            log_error "${MULLE_EXECUTABLE_FAIL_PREFIX}: Unknown option \"$1\""
-            usage "${MULLE_TRACE}"
-         ;;
-
-         *)
-            break
-         ;;
-      esac
-
-      shift
-   done
-
-   options_setup_trace "${MULLE_TRACE}"
-
-   local cmd
-
-   cmd="${1:-update}"
-
-   MULLE_EXECUTABLE_FAIL_PREFIX="${MULLE_EXECUTABLE_NAME} ${cmd}"
-   [ $# -eq 0 ] || shift
-
-   if [ -z "${MULLE_FETCH}" ]
-   then
-      MULLE_FETCH="mulle-fetch"
-   fi
-
-   #
-   #
-   #
-   case "${cmd}" in
-      add)
-         # shellcheck source=src/mulle-sourcetree-config.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
-
-         sourcetree_add_main "$@"
-      ;;
-
-      buildorder)
-         # shellcheck source=src/mulle-sourcetree-walk.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-walk.sh"
-
-         sourcetree_buildorder_main "$@"
-      ;;
-
-      clean)
-         # shellcheck source=src/mulle-sourcetree-db.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-zombie.sh"
-
-         zombie_clean_main "$@"
-      ;;
-
-      dotdump)
-         # shellcheck source=src/mulle-sourcetree-dotdump.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-dotdump.sh"
-
-         sourcetree_dotdump_main "$@"
-      ;;
-
-      fix)
-         # shellcheck source=src/mulle-sourcetree-fix.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-fix.sh"
-
-         sourcetree_fix_main "$@"
-      ;;
-
-      get)
-         # shellcheck source=src/mulle-sourcetree-config.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
-
-         sourcetree_get_main "$@"
-      ;;
-
-      help)
-         usage "${MULLE_TRACE}"
-      ;;
-
-      library-path)
-         echo "${MULLE_SOURCETREE_LIBEXEC_DIR}"
-      ;;
-
-      list)
-         # shellcheck source=src/mulle-sourcetree-config.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
-
-         sourcetree_list_main "$@"
-      ;;
-
-      mark)
-         # shellcheck source=src/mulle-sourcetree-config.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
-
-         sourcetree_mark_main "$@"
-      ;;
-
-      remove)
-         # shellcheck source=src/mulle-sourcetree-config.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
-
-         sourcetree_remove_main "$@"
-      ;;
-
-      reset)
-         # shellcheck source=src/mulle-sourcetree-db.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh"
-
-         db_reset_main "$@"
-      ;;
-
-      set)
-         # shellcheck source=src/mulle-sourcetree-config.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-config.sh"
-
-         sourcetree_set_main "$@"
-      ;;
-
-      status)
-         # shellcheck source=src/mulle-sourcetree-status.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-status.sh"
-
-         sourcetree_status_main "$@"
-      ;;
-
-      uname)
-         echo "${UNAME}"
-      ;;
-
-      update)
-         # shellcheck source=src/mulle-sourcetree-update.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-update.sh"
-
-         sourcetree_update_main "$@"
-      ;;
-
-      walk)
-         # shellcheck source=src/mulle-sourcetree-walk.sh
-         . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-walk.sh"
-
-         sourcetree_walk_main "$@"
-      ;;
-
-      version)
-         echo "${MULLE_EXECUTABLE_VERSION}"
-         return 0
-      ;;
-
-      *)
-         log_error "${MULLE_EXECUTABLE_FAIL_PREFIX}: Unknown command \"${cmd}\""
-         usage "${MULLE_TRACE}"
-      ;;
-   esac
-}
+###
+### INIT
+###
+########
 
 
 _init "$@" # needs params
diff --git a/tests/11-recurse/run-test b/tests/11-recurse/run-test
--- a/tests/11-recurse/run-test
+++ b/tests/11-recurse/run-test
@@ -30,6 +30,7 @@ _setup_demo_repo_a()
 
    redirect_exekutor VERSION echo "2.0.0"
    run_mulle_sourcetree add --nodetype git "file:///${reporoot}/b"
+   [ -f .mulle-sourcetree ] || fail "failed add"
    exekutor git add VERSION .mulle-sourcetree
    exekutor git commit -m "a: version 2.0.0 (tagged)"
    exekutor git tag "2.0.0"
@@ -86,6 +87,7 @@ main()
       cd "${project}"
 
       local a
+      local version
 
       for a in 1.0.0 2.0.0 1.0.0
       do
@@ -96,10 +98,14 @@ main()
 
          run_mulle_sourcetree list
 
-         if ! run_mulle_sourcetree update --recursive
+         if ! run_mulle_sourcetree --recurse update
          then
             fail "update failed unexpectedly"
          fi
+
+
+         version="`cat a/VERSION`"
+         [ "${a}" != "${VERSION}" ] || fail "Checked out version $VERSION instead of $a"
 
          case "${a}" in
             1.0.0)
@@ -140,7 +146,7 @@ init()
    . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
    . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh" || exit 1
    . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-update.sh" || exit 1
-   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-zombify.sh" || exit 1
+   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-zombie.sh" || exit 1
 }
 
 
