rewrite, simplify, improve, break

diff --git a/mulle-sourcetree b/mulle-sourcetree
--- a/mulle-sourcetree
+++ b/mulle-sourcetree
@@ -68,6 +68,7 @@ HIDDEN_COMMANDS="\
    fix           : support to track user modifications in the filesystem
    get           : get a node's properties from the configuration
    library-path  : print path to ${MULLE_EXECUTABLE_NAME} libexec
+   path          : print path to project
    list          : list nodes in the current configuration
    mark          : add or remove a mark from a node in the configuration
    walk          : visit all the tree nodes with a callback
@@ -107,8 +108,12 @@ Usage:
    and archives.
 
 Flags:
+   -e        : bypass mulle-sde check
+   -N        : bypass search for enclosing source tree
+   --flat    : flat operation
+   --recurse : recursive operation
+   --share   : share operation
 EOF
-
    options_technical_flags_usage
 
    cat <<EOF
@@ -150,6 +155,7 @@ main()
    local MULLE_FLAG_LOG_MERGE="NO"
    local MULLE_TRACE_POSTPONE="NO"
    local MULLE_FLAG_DEFER="ROOT"
+   local FLAG_OUTSIDE_ENV="NO"
 
    local FLAG_SOURCETREE_MODE=
 
@@ -157,7 +163,6 @@ main()
    local SOURCETREE_DEFAULT_FILE=".mulle-sourcetree.default"
    local SOURCETREE_DB_DIR=".mulle-sourcetree.db"
    local SOURCETREE_FIX_FILE=".mulle-sourcetree.fix"
-
 
    #
    # simple option handling
@@ -171,6 +176,10 @@ main()
       fi
 
       case "$1" in
+         -e)
+            FLAG_OUTSIDE_ENV="YES"
+         ;;
+
          -f|--force)
             MULLE_FLAG_MAGNUM_FORCE="BOTH"
          ;;
@@ -245,6 +254,11 @@ main()
 
    options_setup_trace "${MULLE_TRACE}"
 
+   if [ "${FLAG_OUTSIDE_ENV}" = "NO" -a -z "${MULLE_SDE_VIRTUAL_ROOT}" ]
+   then
+      fail "To run mulle-sourcetree outside of mulle-sde, pass the -e flag"
+   fi
+
    local cmd
 
    cmd="${1:-update}"
@@ -257,18 +271,24 @@ main()
       MULLE_FETCH="mulle-fetch"
    fi
 
+   # shellcheck source=../mulle-bashfunctions/src/mulle-options.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-path.sh"  || fail "${failmsg}"
+
    # shellcheck source=mulle-sourcetree-db.sh
    . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh" || exit 1
    # shellcheck source=mulle-sourcetree-node.sh
    . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh" || exit 1
    # shellcheck source=mulle-sourcetree-nodeline.sh
    . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh" || exit 1
+   # shellcheck source=mulle-sourcetree-cfg.sh
+   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-cfg.sh" || exit 1
 
-   nodeline_defer_if_needed "ROOT"
+
+   cfg_defer_if_needed "ROOT" || exit 1
 
    local SOURCETREE_MODE
 
-   _db_set_default_mode "${FLAG_SOURCETREE_MODE}"
+   _db_set_default_mode "/" "${FLAG_SOURCETREE_MODE}" || exit 1
 
    #
    #
@@ -285,7 +305,7 @@ main()
          # shellcheck source=src/mulle-sourcetree-walk.sh
          . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-walk.sh"
 
-          "$@"
+         sourcetree_buildorder_main "$@"
       ;;
 
       clean)
@@ -345,12 +365,23 @@ main()
          sourcetree_mark_main "$@"
       ;;
 
+      path)
+         # shellcheck source=src/mulle-sourcetree-walk.sh
+         echo "$PWD"
+      ;;
+
       print)
          # shellcheck source=src/mulle-sourcetree-walk.sh
          . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-walk.sh"
 
+         # promote flat to recurse, except when user says so
+         if [ "${SOURCETREE_MODE}" = "flat" -a -z "${FLAG_SOURCETREE_MODE}" ]
+         then
+            SOURCETREE_MODE="recurse"
+         fi
+
          sourcetree_walk_main --no-depth-first --callback-root --cd \
-               "${MULLE_EXECUTABLE}" --flat -N list --output-eval
+               "${MULLE_EXECUTABLE}" --flat -N list --output-banner --output-eval
       ;;
 
       remove)
@@ -531,20 +562,6 @@ _init()
       fi
       exit 1
    fi
-
-   PATH="${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}:$PATH"
-   PATH="${MULLE_SOURCETREE_LIBEXEC_DIR}:$PATH"
-   export PATH
-
-   if [ ! -z "${MULLE_SOURCETREE_LIBEXEC_TRACE}" ]
-   then
-      echo "PATH=$PATH" >&2
-   fi
-
-   #
-   # to make these includes faster don't search via PATH
-   # but have PATH as fallback
-   #
    local failmsg
 
    failmsg="failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
diff --git a/tests/03-db/run-test b/tests/03-db/run-test
--- a/tests/03-db/run-test
+++ b/tests/03-db/run-test
@@ -21,28 +21,121 @@ main()
    set -e
 
    directory="`make_tmp_directory`" || exit 1
-
-   SOURCETREE_DB_DIR="${directory}"
+   cd "${directory}"
+   SOURCETREE_DB_DIR="db"
 
    local nodeline
    local sourcenodeline
 
-   db_remember 1 "text"
-   nodeline="`db_get_nodeline_for_uuid 1`"
+   # just store some cruft in nodeline, easier for testing
+   db_memorize "/" 1 "text" "" "text"
+
+   nodeline="`db_fetch_nodeline_for_uuid "/" 1`"
+   expect "${nodeline}" "text"
+   nodeline="`db_fetch_filename_for_uuid "/" 1`"
    expect "${nodeline}" "text"
    log_verbose "----- #1 PASSED -----"
 
-   db_remember 2 "other"
-   nodeline="`db_get_nodeline_for_uuid 1`"
+   db_memorize "/" 2 "other" "owner" "owner/other"
+
+   nodeline="`db_fetch_nodeline_for_uuid "/" 1`"
    expect "${nodeline}" "text"
-   nodeline="`db_get_nodeline_for_uuid 2`"
+   nodeline="`db_fetch_nodeline_for_uuid "/" 2`"
    expect "${nodeline}" "other"
+   nodeline="`db_fetch_filename_for_uuid "/" 2`"
+   expect "${nodeline}" "owner/other"
    log_verbose "----- #2 PASSED -----"
 
-   nodeline="`db_get_nodeline_for_uuid 3`"
-   expect "${nodeline}" ""
+   if db_fetch_nodeline_for_uuid "/" 3
+   then
+      fail "did find something unexpectedly"
+   fi
 
    log_verbose "----- #3 PASSED -----"
+
+   #
+   # forget one
+   #
+   if ! db_forget "/" 2
+   then
+      fail "could not forget 2"
+   fi
+
+   if db_fetch_nodeline_for_uuid "/" 2
+   then
+      fail "did not forget"
+   fi
+
+   log_verbose "----- #4 PASSED -----"
+
+
+   #
+   # for zombiefication we need a proper nodeline
+   # with a nodetype
+   if ! db_forget "/" 1
+   then
+      fail "did not forget"
+   fi
+
+   db_memorize "/" 1 "address;git;;1" "the_owner" "the_owner/address"
+
+   mkdir -p the_owner/address
+
+   #
+   # zombify but keeping it alive
+   #
+   if ! db_zombify_nodes "/"
+   then
+      fail "failed to zombify"
+   fi
+
+   if ! db_fetch_nodeline_for_uuid "/" 1 > /dev/null
+   then
+      fail "zombie doesn't respond anymore"
+   fi
+
+   db_set_uuid_alive "/" 1
+
+   if ! db_bury_zombies "/"
+   then
+      fail "failed to bury"
+   fi
+
+   if ! db_fetch_nodeline_for_uuid "/" 1 > /dev/null
+   then
+      fail "alive node unfairly reaped before its time"
+   fi
+
+   [ -d "the_owner/address" ] || fail  "directory vanished"
+
+   log_verbose "----- #5 PASSED -----"
+
+   #
+   # zombify and bury
+   #
+   if ! db_zombify_nodes "/"
+   then
+      fail "failed to zombify"
+   fi
+
+   if ! db_fetch_nodeline_for_uuid "/" 1 > /dev/null
+   then
+      fail "zombie doesn't respond anymore"
+   fi
+
+   if ! db_bury_zombies "/"
+   then
+      fail "failed to bury"
+   fi
+
+   if db_fetch_nodeline_for_uuid "/" 1
+   then
+      fail "survived the zombie apocalypse"
+   fi
+
+   [ ! -d "the_owner/address" ] || fail  "directory still there"
+
+   log_verbose "----- #6 PASSED -----"
 
    log_info "----- ALL PASSED -----"
 
@@ -59,7 +152,9 @@ init()
    MULLE_SOURCETREE="${MULLE_SOURCETREE:-${PWD}/../../mulle-sourcetree}"
    MULLE_SOURCETREE_LIBEXEC_DIR="`${MULLE_SOURCETREE} library-path`" || exit 1
 
-   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh" || exit 1
+   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-node.sh"       || exit 1
+   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-nodeline.sh"       || exit 1
+   . "${MULLE_SOURCETREE_LIBEXEC_DIR}/mulle-sourcetree-db.sh"       || exit 1
 }
 
 
diff --git a/tests/12-share/run-test b/tests/12-share/run-test
--- a/tests/12-share/run-test
+++ b/tests/12-share/run-test
@@ -97,14 +97,14 @@ run_test1()
    then
       fail "add failed unexpectedly"
    fi
-   if ! MULLE_SOURCETREE_SHARED_DIR="shared" run_mulle_sourcetree --recurse --share update
+   if ! MULLE_SOURCETREE_SHARED_DIR="shared" run_mulle_sourcetree --share update
    then
       fail "update failed unexpectedly"
    fi
 
-   [ -d "shared/a" ] || fail "a should exist"
-   [ -d "shared/b" ] || fail "b should exist"
-   [ -d "shared/c" ] || fail "c should exist"
+   [ -d "shared/a" ] || fail "shared/a should exist"
+   [ -d "shared/b" ] || fail "shared/b should exist"
+   [ -d "shared/c" ] || fail "shared/c should exist"
 }
 
 
@@ -120,11 +120,10 @@ run_test2()
       fail "update failed unexpectedly"
    fi
 
-   [ -d "shared/a" ] || fail "a should exist"
-   [ -d "shared/b" ] || fail "b should exist"
-   [ -d "shared/c" ] || fail "c should exist"
+   [ -d "shared/a" ] || fail "shared/a should exist"
+   [ -d "shared/b" ] || fail "shared/b should exist"
+   [ -d "shared/c" ] || fail "shared/c should exist"
 }
-
 
 
 run_test3()
@@ -135,19 +134,24 @@ run_test3()
    then
       fail "add failed unexpectedly"
    fi
-   if ! MULLE_SOURCETREE_SHARED_DIR="shared" run_mulle_sourcetree ${flags} --share  update
+
+   run_mulle_sourcetree list
+
+   if ! MULLE_SOURCETREE_SHARED_DIR="shared" run_mulle_sourcetree ${flags} --share update
    then
       fail "update failed unexpectedly"
    fi
 
    if [ -z ${flags} ]
    then
-      [ -d "shared/a" ]   || fail "a should exist"
-      [ ! -d "shared/b" ] || fail "b should not exist"
-      [ -d "shared/c" ]   || fail "c should exist"
+      [ -d "shared/a" ]     || fail "shared/a should exist"
+      [ -d "shared/b" ]     && fail "shared/b should not exist"
+      [ -d "shared/c" ]     || fail "shared/c should exist"
 
-      [ -d "shared/a/b" ]   || fail "a/b should exist"
-      [ -d "shared/a/b/c" ] || fail "a/b/c should exist"
+      [ -d "shared/a/b" ]   || fail "shared/a/b should exist"
+
+      # this is debatable i don't know
+      # [ -d "shared/a/b/c" ] || fail "shared/a/b/c should exist"
    fi
 }
 
@@ -162,6 +166,8 @@ main()
    local directory
 
    directory="`make_tmp_directory`" || exit 1
+   MULLE_SDE_VIRTUAL_ROOT="${directory}"
+   export MULLE_SDE_VIRTUAL_ROOT
 
    local project
 
