don't use url as node identifier, use the destination (duh)

diff --git a/tests/10-simple/run-test b/tests/10-simple/run-test
--- a/tests/10-simple/run-test
+++ b/tests/10-simple/run-test
@@ -47,35 +47,35 @@ setup_demo_repos()
 
 test_bad_paths()
 {
-   if run_mulle_sourcetree add "${repos}/a" "/tmp/foo"
+   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "/tmp/foo"
    then
       fail "failed to complain about absolute path"
    fi
    [ -e ".mulle-sourcetree" ]    && fail "a: .mulle-sourcetree should not exist"
    [ -e ".mulle-sourcetree.db" ] && fail "a: .mulle-sourcetree.db should not exist"
 
-   if run_mulle_sourcetree add "${repos}/a" "../foo"
+   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "../foo"
    then
       fail "failed to complain about escape path"
    fi
    [ -e ".mulle-sourcetree" ]    && fail "b: .mulle-sourcetree should not exist"
    [ -e ".mulle-sourcetree.db" ] && fail "b: .mulle-sourcetree.db should not exist"
 
-   if run_mulle_sourcetree add "${repos}/a" "a/../.."
+   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "a/../.."
    then
       fail "failed to complain about escape path"
    fi
    [ -e ".mulle-sourcetree" ]    && fail "c: .mulle-sourcetree should not exist"
    [ -e ".mulle-sourcetree.db" ] && fail "c: .mulle-sourcetree.db should not exist"
 
-   if run_mulle_sourcetree add "${repos}/a" "~foo"
+   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "~foo"
    then
       fail "failed to complain about absolute path"
    fi
    [ -e ".mulle-sourcetree" ]    && fail "d: .mulle-sourcetree should not exist"
    [ -e ".mulle-sourcetree.db" ] && fail "d: .mulle-sourcetree.db should not exist"
 
-   if run_mulle_sourcetree add "${repos}/a" "~/foo"
+   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "~/foo"
    then
       fail "failed to complain about absolute path"
    fi
@@ -88,7 +88,7 @@ test_bad_paths()
 
 test_simple_add_remove()
 {
-   if ! run_mulle_sourcetree add --branch release "${repos}/a" "foo"
+   if ! run_mulle_sourcetree add --nodetype git --branch release --url "${repos}/a" "foo"
    then
       fail "failed unexpectedly"
    fi
@@ -96,19 +96,19 @@ test_simple_add_remove()
    [ -e ".mulle-sourcetree.db" ] && fail "a: .mulle-sourcetree.db should not exist"
 
    # same url should not work
-   if run_mulle_sourcetree add "${repos}/a" "foo"
+   if run_mulle_sourcetree add --nodetype git --url "${repos}/a" "foo"
    then
       fail "succeeded unexpectedly"
    fi
-   [ -f ".mulle-sourcetree" ]    || fail "a: .mulle-sourcetree should exist now"
-   [ -e ".mulle-sourcetree.db" ] && fail "a: .mulle-sourcetree.db should not exist"
+   [ -f ".mulle-sourcetree" ]    || fail "b: .mulle-sourcetree should exist now"
+   [ -e ".mulle-sourcetree.db" ] && fail "b: .mulle-sourcetree.db should not exist"
 
-   if ! run_mulle_sourcetree remove "${repos}/a"
+   if ! run_mulle_sourcetree remove "foo"
    then
       fail "failed unexpectedly"
    fi
-   [ -e ".mulle-sourcetree" ]    && fail "b: .mulle-sourcetree should not exist anymore"
-   [ -e ".mulle-sourcetree.db" ] && fail "b: .mulle-sourcetree.db should not exist"
+   [ -e ".mulle-sourcetree" ]    && fail "c: .mulle-sourcetree should not exist anymore"
+   [ -e ".mulle-sourcetree.db" ] && fail "c: .mulle-sourcetree.db should not exist"
 
    :
 }
@@ -120,7 +120,7 @@ test_update1()
    [ -e ".mulle-sourcetree.db" ] && fail "a: .mulle-sourcetree.db should not exist"
    [ -e "foo" ]                  && fail "a: foo should not exist"
 
-   if ! run_mulle_sourcetree add --branch release "${repos}/a" "foo"
+   if ! run_mulle_sourcetree add --nodetype git --branch release --url "${repos}/a" "foo"
    then
       fail "add failed unexpectedly"
    fi
@@ -136,16 +136,16 @@ test_update1()
 
    [ -e ".mulle-sourcetree" ]    || fail "c: .mulle-sourcetree should exist"
    [ -e ".mulle-sourcetree.db" ] || fail "c: .mulle-sourcetree.db should exist"
-   [ -f "foo/VERSION" ]  || fail "c: foo/VERSION should exist"
+   [ -f "foo/VERSION" ]          || fail "c: foo/VERSION should exist"
 
-   if ! run_mulle_sourcetree remove "${repos}/a"
+   if ! run_mulle_sourcetree remove "foo"
    then
       fail "remove failed unexpectedly"
    fi
 
    [ -e ".mulle-sourcetree" ]    && fail "d: .mulle-sourcetree should not exist anymore"
    [ -e ".mulle-sourcetree.db" ] || fail "d: .mulle-sourcetree.db should exist"
-   [ -f "foo/VERSION" ]  || fail "d: foo/VERSION should exist"
+   [ -f "foo/VERSION" ]          || fail "d: foo/VERSION should exist"
 
    if ! run_mulle_sourcetree update
    then
@@ -171,7 +171,7 @@ test_update2()
    [ -e ".mulle-sourcetree.db" ] && fail "a: .mulle-sourcetree.db should not exist"
    [ -e "foo" ]                  && fail "a: foo should not exist"
 
-   if ! run_mulle_sourcetree add --branch release "${repos}/a" "foo"
+   if ! run_mulle_sourcetree add --nodetype git --branch release --url "${repos}/a" "foo"
    then
       fail "add failed unexpectedly"
    fi
@@ -187,17 +187,17 @@ test_update2()
 
    [ -e ".mulle-sourcetree" ]    || fail "c: .mulle-sourcetree should exist"
    [ -e ".mulle-sourcetree.db" ] || fail "c: .mulle-sourcetree.db should exist"
-   [ -f "foo/VERSION" ]  || fail "c: foo/VERSION should exist"
+   [ -f "foo/VERSION" ]          || fail "c: foo/VERSION should exist"
 
-   if ! run_mulle_sourcetree set --destination "bar" "${repos}/a"
+   if ! run_mulle_sourcetree set --address "bar"  foo
    then
-      fail "remove failed unexpectedly"
+      fail "set failed unexpectedly"
    fi
 
    [ -e ".mulle-sourcetree" ]    || fail "d: .mulle-sourcetree should exist"
    [ -e ".mulle-sourcetree.db" ] || fail "d: .mulle-sourcetree.db should exist"
-   [ -f "foo/VERSION" ]  || fail "d: foo/VERSION should exist"
-   [ -f "bar/VERSION" ]  && fail "d: bar/VERSION should not exist"
+   [ -f "foo/VERSION" ]          || fail "d: foo/VERSION should exist"
+   [ -f "bar/VERSION" ]          && fail "d: bar/VERSION should not exist"
 
    if ! run_mulle_sourcetree update
    then
@@ -206,8 +206,8 @@ test_update2()
 
    [ -e ".mulle-sourcetree" ]    || fail "e: .mulle-sourcetree should exist"
    [ -e ".mulle-sourcetree.db" ] || fail "e: .mulle-sourcetree.db should exist"
-   [ -f "foo/VERSION" ]  && fail "e: foo/VERSION should exist"
-   [ -f "bar/VERSION" ]  || fail "e: bar/VERSION should exist"
+   [ -f "foo/VERSION" ]          && fail "e: foo/VERSION should exist"
+   [ -f "bar/VERSION" ]          || fail "e: bar/VERSION should exist"
 
    :
 }
